server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        model: text-embedding-3-small
  data:
    mongodb:
      uri: mongodb://localhost:27017

# Application specific configuration
app:
  mongodb:
    database: features_repo